"use client";
import { OnboardingStepper } from "@/components/ui/ix-onboarding-stepper";
import benchmarkFixture from "../../benchmark/fixture.json";
import { useRef, useState, type ReactNode, type RefObject } from "react";
import { ArrowRightIcon, BuildingIcon, CandlestickChartIcon, CheckCircleIcon, FlashIcon, NavArrowRightIcon, PlusIcon, RefreshIcon, UserIcon } from "@/components/icons";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

const nav = [["Companies", "#companies", BuildingIcon], ["People", "#people", UserIcon], ["Deals", "#deals", CandlestickChartIcon], ["Workflows", "#workflows", FlashIcon]] as const;
const stats = [["Active deals", "38"], ["Needs follow-up", "11"], ["Pipeline", "$284k"]];
const records = [["Acme Works", "Expansion · $32k", "No activity for 4 days", "Follow up"], ["Orbit Health", "New business · $46k", "Call tomorrow", "Qualified"], ["Sora Labs", "New business · $18k", "Proposal viewed", "Proposal"]];
const steps = ["Workflows", "Choose a trigger", "Review actions", "Workflow published"];
type FormState = { name: string; trigger: string; stage: string; wait: string; note: string };
const initialForm: FormState = { name: "", trigger: "", stage: "", wait: "", note: "" };





function BenchmarkStepper({
  currentStep,
  onStepChange,
}: {
  currentStep: number;
  onStepChange: (step: number) => void;
}) {
  const benchmarkSteps = benchmarkFixture.steps.map((item, index) => ({
    id: String(index),
    label: item.title,
    title: item.title,
    description: item.description,
  }));

  return (
    <OnboardingStepper
      steps={benchmarkSteps}
      index={currentStep}
      onIndexChange={(nextStep) => {
        if (nextStep < currentStep) onStepChange(nextStep);
      }}
      progressStyle="segments"
      labelMode="current"
      progressLabel={benchmarkFixture.name + " progress"}
      className="mb-8 shadow-none [&>div:nth-of-type(2)]:hidden [&>div:last-child]:hidden"
    />
  );
}

export default function Home() {
  const [step, setStep] = useState(0); const [form, setForm] = useState(initialForm); const [errors, setErrors] = useState<Record<string, string>>({}); const firstInvalid = useRef<HTMLInputElement>(null);
  const update = (field: keyof FormState, value: string) => { setForm((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: "" })); };
  const validate = () => { const next: Record<string, string> = {}; if (!form.name.trim()) next.name = "Enter a workflow name."; if (!form.trigger) next.trigger = "Choose a trigger."; if (!form.stage) next.stage = "Choose a stage."; if (!form.wait || Number(form.wait) < 1) next.wait = "Enter a wait of at least 1 day."; setErrors(next); if (Object.keys(next).length) { requestAnimationFrame(() => firstInvalid.current?.focus()); return false; } return true; };
  const next = () => { if (step === 1 && !validate()) return; setStep((current) => Math.min(3, current + 1)); requestAnimationFrame(() => document.getElementById("main-content")?.focus()); };
  const reset = () => { setForm(initialForm); setErrors({}); setStep(0); };
  return <div className="min-h-dvh bg-background text-foreground"><a className="skip-link" href="#main-content">Skip to content</a><header className="border-b border-border bg-card"><div className="mx-auto flex min-h-16 max-w-[1440px] items-center justify-between gap-5 px-4 sm:px-8"><a href="#workflows" className="flex min-h-11 items-center gap-3 font-semibold tracking-tight" aria-label="Northstar home"><span className="grid size-8 place-items-center rounded-md bg-primary text-primary-foreground"><FlashIcon className="size-4" /></span>Northstar</a><div className="hidden items-center gap-2 text-sm text-muted-foreground md:flex"><span>Revenue operations</span><NavArrowRightIcon className="size-4" /><span>Workflow setup</span></div><Button variant="outline" size="sm" onClick={reset}><RefreshIcon className="size-4" /> Reset</Button></div></header><div className="mx-auto flex max-w-[1440px] flex-col md:flex-row"><aside className="border-b border-border bg-card md:min-h-[calc(100dvh-4rem)] md:w-60 md:shrink-0 md:border-b-0 md:border-r"><nav aria-label="Primary navigation" className="flex gap-1 overflow-x-auto p-3 md:block md:space-y-1 md:p-5">{nav.map(([label, href, Icon]) => <a key={label} href={href} aria-current={label === "Workflows" ? "page" : undefined} className={`nav-link ${label === "Workflows" ? "nav-link-active" : ""}`}><Icon className="size-[18px]" /><span>{label}</span></a>)}</nav><div className="hidden border-t border-border p-5 md:block"><p className="text-sm font-medium">This week</p><p className="mt-1 text-sm text-muted-foreground">11 deals need follow-up.</p></div></aside><main id="main-content" tabIndex={-1} className="min-w-0 flex-1 outline-none"><div className="mx-auto max-w-5xl px-4 py-7 sm:px-8 sm:py-10"><BenchmarkStepper currentStep={step} onStepChange={(nextStep) => setStep(nextStep as typeof step)} />{step === 0 && <Overview onContinue={next} />}{step === 1 && <DataEntry form={form} errors={errors} firstInvalid={firstInvalid} update={update} onBack={() => setStep(0)} onContinue={next} />}{step === 2 && <Review form={form} update={update} onBack={() => setStep(1)} onContinue={next} />}{step === 3 && <Complete form={form} onReset={reset} />}</div></main></div></div>;
}
function StepHeader({ current }: { current: number }) { return <div className="hidden" aria-hidden="true"><div className="mb-9"><div className="mb-5 flex items-center justify-between gap-4"><p className="text-sm font-medium text-primary">Step {current + 1} of 4</p><p className="text-sm text-muted-foreground">{Math.round(((current + 1) / 4) * 100)}% complete</p></div><Progress value={((current + 1) / 4) * 100} aria-label={`${current + 1} of 4 steps complete`} /><div className="mt-4 grid grid-cols-4 gap-2">{steps.map((title, index) => <div key={title} className={`text-xs sm:text-sm ${index <= current ? "font-medium text-foreground" : "text-muted-foreground"}`}><span className={`mr-1 inline-grid size-5 place-items-center rounded-full text-xs ${index < current ? "bg-primary text-primary-foreground" : index === current ? "border border-primary text-primary" : "border border-border"}`}>{index < current ? "✓" : index + 1}</span>{title}</div>)}</div></div></div>; }
function Overview({ onContinue }: { onContinue: () => void }) { return <><StepHeader current={0} /><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Workflows</h1><p className="mt-2 max-w-xl text-base text-muted-foreground">Automate the follow-up work that protects pipeline momentum.</p></div><Button size="lg" onClick={onContinue}><PlusIcon className="size-4" /> Create workflow <ArrowRightIcon className="size-4" /></Button></div><div className="grid gap-3 sm:grid-cols-3">{stats.map(([label, value]) => <Card key={label}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p></CardContent></Card>)}</div><Card className="mt-8"><CardHeader><CardTitle className="text-xl">Deals needing attention</CardTitle><CardDescription>Recent pipeline activity that could benefit from a workflow.</CardDescription></CardHeader><CardContent className="space-y-2">{records.map(([title, detail, meta, status]) => <div key={title} className="flex flex-col gap-2 border-t border-border py-4 first:border-t-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{detail} · {meta}</p></div><Badge variant="secondary" className="w-fit">{status}</Badge></div>)}</CardContent></Card></>; }
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <div className="space-y-2"><Label>{label} <span className="text-destructive">*</span></Label>{children}{error && <p className="text-sm font-medium text-destructive" role="alert">{error}</p>}</div>; }
function SelectField({ id, label, value, placeholder, options, error, onChange }: { id: string; label: string; value: string; placeholder: string; options: string[]; error?: string; onChange: (value: string) => void }) { return <Field label={label} error={error}><Select value={value} onValueChange={onChange}><SelectTrigger id={id} aria-invalid={Boolean(error)}><SelectValue placeholder={placeholder} /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select></Field>; }
function DataEntry({ form, errors, firstInvalid, update, onBack, onContinue }: { form: FormState; errors: Record<string, string>; firstInvalid: RefObject<HTMLInputElement | null>; update: (field: keyof FormState, value: string) => void; onBack: () => void; onContinue: () => void }) { return <><StepHeader current={1} /><div className="max-w-2xl"><h1 className="text-3xl font-semibold tracking-tight">Choose a trigger</h1><p className="mt-2 text-base text-muted-foreground">Start when a deal enters the qualified stage.</p><Card className="mt-8"><CardHeader><CardTitle className="text-xl">Workflow details</CardTitle><CardDescription>All fields are required to create this workflow.</CardDescription></CardHeader><CardContent className="space-y-6"><Field label="Workflow name" error={errors.name}><Input ref={firstInvalid} id="workflow-name" value={form.name} placeholder="Qualified deal follow-up" aria-invalid={Boolean(errors.name)} onChange={(event) => update("name", event.target.value)} /></Field><SelectField id="trigger" label="Trigger" value={form.trigger} placeholder="Deal enters stage" options={["Deal enters stage", "Deal value changes", "No activity"]} error={errors.trigger} onChange={(value) => update("trigger", value)} /><SelectField id="stage" label="Stage" value={form.stage} placeholder="Qualified" options={["Qualified", "Proposal", "Negotiation"]} error={errors.stage} onChange={(value) => update("stage", value)} /><Field label="Wait" error={errors.wait}><div className="flex max-w-xs items-center gap-3"><Input id="wait" type="number" min="1" inputMode="numeric" value={form.wait} placeholder="2" aria-invalid={Boolean(errors.wait)} onChange={(event) => update("wait", event.target.value)} /><span className="text-base text-muted-foreground">days</span></div></Field></CardContent><div className="flex flex-col-reverse gap-3 border-t border-border p-6 sm:flex-row sm:justify-between"><Button variant="outline" onClick={onBack}>Back</Button><Button onClick={onContinue}>Add actions <ArrowRightIcon className="size-4" /></Button></div></Card></div></>; }
function Review({ form, update, onBack, onContinue }: { form: FormState; update: (field: keyof FormState, value: string) => void; onBack: () => void; onContinue: () => void }) { return <><StepHeader current={2} /><div className="max-w-2xl"><h1 className="text-3xl font-semibold tracking-tight">Review actions</h1><p className="mt-2 text-base text-muted-foreground">Wait {form.wait || "—"} days, create a task, and notify the owner.</p><Card className="mt-8"><CardHeader><CardTitle className="text-xl">{form.name || "Untitled workflow"}</CardTitle><CardDescription>When a deal enters {form.stage || "the selected stage"}</CardDescription></CardHeader><CardContent className="space-y-3"><ReviewRow title={`Wait ${form.wait || "—"} days`} detail="Give the owner time to respond." /><ReviewRow title="Create a follow-up task" detail="Assign a task to the deal owner." /><ReviewRow title="Notify the owner" detail="Send an in-app notification." /><div className="mt-7 space-y-2"><Label htmlFor="internal-note">Internal note <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="internal-note" rows={4} value={form.note} placeholder="Add context for the sales team" onChange={(event) => update("note", event.target.value)} /></div></CardContent><div className="flex flex-col-reverse gap-3 border-t border-border p-6 sm:flex-row sm:justify-between"><Button variant="outline" onClick={onBack}>Back</Button><Button onClick={onContinue}>Publish workflow <ArrowRightIcon className="size-4" /></Button></div></Card></div></>; }
function ReviewRow({ title, detail }: { title: string; detail: string }) { return <div className="flex gap-3 rounded-md border border-border bg-muted/40 p-4"><CheckCircleIcon className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{detail}</p></div></div>; }
function Complete({ form, onReset }: { form: FormState; onReset: () => void }) { return <><StepHeader current={3} /><Card className="max-w-2xl"><CardContent className="p-7 sm:p-10"><div className="grid size-12 place-items-center rounded-full bg-primary/10 text-primary"><CheckCircleIcon className="size-7" /></div><h1 className="mt-6 text-3xl font-semibold tracking-tight">Workflow published</h1><p className="mt-3 max-w-lg text-base text-muted-foreground">{form.name || "Qualified deal follow-up"} is active for new matching deals.</p><div className="mt-8 rounded-md border border-border bg-muted/40 p-4 text-sm"><p className="font-medium">Next step</p><p className="mt-1 text-muted-foreground">Northstar will run this workflow when a deal enters {form.stage || "Qualified"}.</p></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button onClick={onReset}>View workflow <ArrowRightIcon className="size-4" /></Button><Button variant="outline" onClick={onReset}><RefreshIcon className="size-4" /> Create another</Button></div></CardContent></Card></>; }
