"use client";
import { OnboardingStepper } from "@/components/ui/ix-onboarding-stepper";
import benchmarkFixture from "../../benchmark/fixture.json";
import { useRef, useState } from "react";
import { ArrowLeftDuotoneIcon, ArrowRightDuotoneIcon, CalendarDuotoneIcon, CheckDuotoneIcon, ClockDuotoneIcon, NoteDuotoneIcon, UsersDuotoneIcon, WarningCircleDuotoneIcon } from "@/components/icons";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
type Details={candidate:string;type:string;duration:string;date:string;note:string};
type RequiredField="candidate"|"type"|"duration"|"date";
const empty:Details={candidate:"",type:"",duration:"",date:"",note:""};
const nav=["Events","Availability","Teams","Analytics"];
const records=[["Product designer panel","Jamie Park","4 interviewers","Needs time"],["Engineering screen","Morgan Lee","Tomorrow at 14:30","Confirmed"],["Culture interview","Taylor Reed","Fri at 10:00","Confirmed"]];




function BenchmarkStepper({
  currentStep,
  onStepChange,
}: {
  currentStep: number;
  onStepChange: (step: number) => void;
}) {
  const benchmarkSteps = benchmarkFixture.steps.map((item, index) => ({
    id: String(index),
    label: item.title,
    title: item.title,
    description: item.description,
  }));

  return (
    <OnboardingStepper
      steps={benchmarkSteps}
      index={currentStep}
      onIndexChange={(nextStep) => {
        if (nextStep < currentStep) onStepChange(nextStep);
      }}
      progressStyle="segments"
      labelMode="current"
      progressLabel={benchmarkFixture.name + " progress"}
      className="mb-8 shadow-none [&>div:nth-of-type(2)]:hidden [&>div:last-child]:hidden"
    />
  );
}

export default function Home(){
 const [step,setStep]=useState(1),[details,setDetails]=useState(empty),[errors,setErrors]=useState<Partial<Record<keyof Details,string>>>({}),[active,setActive]=useState("Events"),[time,setTime]=useState("Tomorrow, 14:30–15:30");
 const fieldRefs=useRef<Partial<Record<RequiredField,HTMLElement|null>>>({}); const update=(key:keyof Details,value:string)=>setDetails(d=>({...d,[key]:value}));
 const validate=()=>{const next:typeof errors={};(["candidate","type","duration","date"] as const).forEach(k=>{if(!details[k].trim())next[k]=`${k[0].toUpperCase()+k.slice(1)} is required.`});setErrors(next);const firstInvalid=(["candidate","type","duration","date"] as const).find(k=>next[k]);if(firstInvalid){setTimeout(()=>fieldRefs.current[firstInvalid]?.focus(),0);return false}return true};
 const forward=()=>{if(step===2&&!validate())return;setStep(s=>Math.min(4,s+1));window.scrollTo({top:0,behavior:"smooth"})}; const reset=()=>{setDetails(empty);setErrors({});setStep(1)};
 const error=(k:keyof Details)=>errors[k]&&<p id={`${k}-error`} role="alert" className="mt-2 flex items-center gap-1 text-sm font-medium text-destructive"><WarningCircleDuotoneIcon className="size-4"/>{errors[k]}</p>;
 return <div className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-card"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8"><a href="#top" className="flex min-h-11 items-center gap-2 text-lg font-semibold"><span className="grid size-9 place-items-center rounded-lg bg-primary text-primary-foreground"><CalendarDuotoneIcon className="size-5"/></span>Tempo</a><nav aria-label="Main navigation" className="hidden gap-1 md:flex">{nav.map(n=><Button key={n} variant={active===n?"secondary":"ghost"} className="min-h-11" onClick={()=>setActive(n)}>{n}</Button>)}</nav></div><div className="mx-auto flex gap-1 overflow-x-auto px-4 pb-3 md:hidden">{nav.map(n=><Button key={n} size="sm" variant={active===n?"secondary":"ghost"} className="min-h-11 shrink-0" onClick={()=>setActive(n)}>{n}</Button>)}</div></header>
 <main id="top" className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0"><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{["Interview schedule","Interview details","Choose a time","Interview confirmed"][step-1]}</h1><p className="mt-2 max-w-2xl text-base text-muted-foreground">{["See confirmed interviews and candidates who still need a time.","Choose the candidate, interview type, and interview day.","Compare panel availability and select the best slot.","Jamie and the panel received calendar invitations."][step-1]}</p><><BenchmarkStepper currentStep={step - 1} onStepChange={(nextStep) => setStep((nextStep + 1) as typeof step)} /><div className="hidden" aria-hidden="true"><Progress value={step*25} className="my-8 h-2" aria-label={`Step ${step} of 4`}/></div></><div className="hidden" aria-hidden="true"><nav aria-label="Scheduling progress"><ol className="grid grid-cols-4 gap-2">{["Schedule","Details","Time","Done"].map((n,i)=>{const completed=i+1<step; const current=i+1===step; return <li key={n} className={`flex items-center gap-2 text-sm ${completed||current?"font-semibold":"text-muted-foreground"}`} aria-current={current?"step":undefined}><span className={`grid size-8 shrink-0 place-items-center rounded-full border ${completed?"border-primary bg-primary text-primary-foreground":current?"border-primary text-primary":"border-border"}`}>{completed?<CheckDuotoneIcon className="size-4"/>:i+1}</span><span className="hidden sm:inline">{n}</span></li>})}</ol></nav></div><div className="mt-8">
 {step===1&&<><Card><CardHeader><CardTitle>Needs scheduling</CardTitle></CardHeader><CardContent className="space-y-3">{records.map(([title,detail,meta,status])=><div key={title} className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><UsersDuotoneIcon className="mt-1 size-5 shrink-0 text-primary"/><div><h2 className="font-semibold">{title}</h2><p aria-label={`${detail}, ${meta}`} className="text-base text-muted-foreground"><span>{detail}</span><span className="text-sm">{meta}</span></p></div></div><Badge variant={status==="Confirmed"?"secondary":"default"} className="w-fit py-1">{status}</Badge></div>)}</CardContent></Card><div className="mt-6 flex justify-end"><Button size="lg" className="min-h-11" onClick={forward}>Schedule interview<ArrowRightDuotoneIcon className="size-5"/></Button></div></>}
 {step===2&&<Card><CardHeader><CardTitle>Interview details</CardTitle></CardHeader><CardContent><form className="space-y-5" noValidate onSubmit={e=>{e.preventDefault();forward()}}><div><Label htmlFor="candidate">Candidate *</Label><Input ref={node=>{fieldRefs.current.candidate=node}} id="candidate" value={details.candidate} onChange={e=>update("candidate",e.target.value)} aria-invalid={!!errors.candidate} aria-describedby={errors.candidate?"candidate-error":undefined} required className="mt-2 min-h-12 text-base" placeholder="Jamie Park"/>{error("candidate")}</div><div><Label htmlFor="type">Interview type *</Label><Select value={details.type} onValueChange={v=>update("type",v)}><SelectTrigger ref={node=>{fieldRefs.current.type=node}} id="type" aria-invalid={!!errors.type} aria-describedby={errors.type?"type-error":undefined} className="mt-2 min-h-12 text-base"><SelectValue placeholder="Choose an interview type"/></SelectTrigger><SelectContent>{["Panel interview","Screen","Culture interview"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>{error("type")}</div><div><Label htmlFor="duration">Duration *</Label><Select value={details.duration} onValueChange={v=>update("duration",v)}><SelectTrigger ref={node=>{fieldRefs.current.duration=node}} id="duration" aria-invalid={!!errors.duration} aria-describedby={errors.duration?"duration-error":undefined} className="mt-2 min-h-12 text-base"><SelectValue placeholder="Choose a duration"/></SelectTrigger><SelectContent>{["30 minutes","45 minutes","60 minutes"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>{error("duration")}</div><div><Label htmlFor="date">Date *</Label><Input ref={node=>{fieldRefs.current.date=node}} id="date" type="date" value={details.date} onChange={e=>update("date",e.target.value)} aria-invalid={!!errors.date} aria-describedby={errors.date?"date-error":undefined} required className="mt-2 min-h-12 text-base"/>{error("date")}</div><div><Label htmlFor="note">Internal note <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="note" value={details.note} onChange={e=>update("note",e.target.value)} placeholder="Add context for the panel" className="mt-2 min-h-24 text-base"/></div><div className="flex flex-col-reverse gap-3 border-t pt-5 sm:flex-row sm:justify-between"><Button type="button" variant="ghost" className="min-h-11" onClick={()=>setStep(1)}><ArrowLeftDuotoneIcon className="size-5"/>Back</Button><Button type="submit" size="lg" className="min-h-11">Find times<ArrowRightDuotoneIcon className="size-5"/></Button></div></form></CardContent></Card>}
 {step===3&&<Card><CardHeader><CardTitle>Available times</CardTitle></CardHeader><CardContent><section aria-labelledby="review-heading" className="mb-6 rounded-lg border bg-muted/40 p-4"><div className="flex items-center gap-2"><NoteDuotoneIcon className="size-5 text-primary"/><h3 id="review-heading" className="font-semibold">Review interview details</h3></div><dl className="mt-4 grid gap-3 text-base sm:grid-cols-2"><div><dt className="text-muted-foreground">Candidate</dt><dd className="font-medium">{details.candidate}</dd></div><div><dt className="text-muted-foreground">Interview type</dt><dd className="font-medium">{details.type}</dd></div><div><dt className="text-muted-foreground">Duration</dt><dd className="font-medium">{details.duration}</dd></div><div><dt className="text-muted-foreground">Date</dt><dd className="font-medium">{new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(`${details.date}T00:00:00`))}</dd></div>{details.note&&<div className="sm:col-span-2"><dt className="text-muted-foreground">Internal note</dt><dd className="font-medium">{details.note}</dd></div>}</dl></section><div className="grid gap-3 sm:grid-cols-3">{["Tomorrow, 14:30–15:30","Tomorrow, 16:00–17:00","Thursday, 09:00–10:00"].map(x=><button type="button" key={x} onClick={()=>setTime(x)} aria-pressed={time===x} className={`min-h-16 rounded-lg border p-3 text-left text-base focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${time===x?"border-primary bg-accent font-semibold":"hover:bg-muted"}`}><ClockDuotoneIcon className="mb-1 size-5 text-primary"/>{x}</button>)}</div><p className="mt-5 rounded-lg bg-muted p-4 text-base text-muted-foreground">All four interviewers are available for the selected time.</p><div className="mt-6 flex flex-col-reverse gap-3 border-t pt-5 sm:flex-row sm:justify-between"><Button variant="ghost" className="min-h-11" onClick={()=>setStep(2)}><ArrowLeftDuotoneIcon className="size-5"/>Back</Button><Button size="lg" className="min-h-11" onClick={forward}>Confirm interview<CheckDuotoneIcon className="size-5"/></Button></div></CardContent></Card>}
 {step===4&&<Card><CardContent className="flex flex-col items-center px-5 py-12 text-center"><span className="mb-5 grid size-16 place-items-center rounded-full bg-primary text-primary-foreground"><CheckDuotoneIcon className="size-9"/></span><h2 className="text-2xl font-semibold">Interview confirmed</h2><p className="mt-2 text-base text-muted-foreground">Calendar invitations are on their way to {details.candidate||"Jamie Park"} and the panel.</p><div className="mt-7 grid w-full max-w-md gap-3 rounded-lg border p-4 text-left text-base sm:grid-cols-2"><span className="text-muted-foreground">Time</span><span className="font-medium sm:text-right">{time}</span><span className="text-muted-foreground">Interview</span><span className="font-medium sm:text-right">{details.type||"Panel interview"}</span>{details.note&&<><span className="text-muted-foreground">Internal note</span><span className="font-medium sm:text-right">{details.note}</span></>}</div><Button variant="outline" size="lg" className="mt-7 min-h-11" onClick={reset}>Schedule another interview</Button></CardContent></Card>}
 </div></div><aside className="space-y-4 lg:pt-16"><Card><CardHeader><CardTitle className="text-base">This week</CardTitle></CardHeader><CardContent className="grid grid-cols-3 gap-3">{[{v:"14",l:"Interviews this week",I:CalendarDuotoneIcon},{v:"6",l:"Needs scheduling",I:ClockDuotoneIcon},{v:"2",l:"Conflicts",I:WarningCircleDuotoneIcon}].map(({v,l,I})=><div key={l}><I className="mb-2 size-5 text-primary"/><p className="text-2xl font-semibold">{v}</p><p className="text-sm leading-tight text-muted-foreground">{l}</p></div>)}</CardContent></Card></aside></div></main></div>;
}
